version: '3.8'

services:
  auth-api:
    build: auth_api
    container_name: auth
    ports:
      - "3001:3001"
  store-api:
    build: ./store_api
    container_name: store
    ports:
      - "3002:3002"
  player-api:
    build: ./player_api
    container_name: player
    ports:
      - "3003:3003"
  match-api:
    build: ./match_api
    container_name: match
    ports:
      - "3004:3004"